# Generated by Django 4.2 on 2023-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_urun_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunresmi',
            field=models.ImageField(default='Belirli bir resim yok', upload_to='urunphoto/'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(default='Belirli bir kategori yok', max_length=100),
        ),
    ]
