# Generated by Django 4.2.3 on 2023-08-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productsapp', '0039_remove_kurulum_videobaslik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odendi_mi', models.BooleanField(default=False)),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('odeme_tarihi', models.DateField(blank=True, null=True)),
                ('sepet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productsapp.sepet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
