# Generated by Django 4.2.3 on 2023-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0050_siparis_teslimat_bilgileri_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='gonderim_bilgisi',
        ),
        migrations.AddField(
            model_name='siparis',
            name='kargoya_verildi',
            field=models.BooleanField(default=False, verbose_name='Kargoya Verildi'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='siparis_iptal',
            field=models.BooleanField(default=False, verbose_name='Sipariş İptal'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='siparis_teslim_edildi',
            field=models.BooleanField(default=False, verbose_name='Sipariş Teslim Edildi'),
        ),
    ]
