# Generated by Django 4.2 on 2023-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.TextField(default='Belirli bir kategori yok', max_length=100),
        ),
    ]
