# Generated by Django 4.2 on 2023-06-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_alter_urun_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunresmiFour',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunresmiThree',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunresmiTwo',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/'),
        ),
    ]
