# Generated by Django 4.2 on 2023-06-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_urun_stokkodu_urun_urunrengi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
