# Generated by Django 4.2 on 2023-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0015_socialmedia_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='company_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
