# Generated by Django 4.1.7 on 2023-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0022_alter_urun_ayakkaplama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anakategori',
            name='anakategoriGorsel',
            field=models.ImageField(upload_to='anakategoriphoto/'),
        ),
    ]
