# Generated by Django 4.2.3 on 2023-07-18 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0025_alter_sepet_toplam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Sosyal Medyalar'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='urun',
            name='teknikDetaylar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Teknik Detaylar'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ayakKaplama',
            field=models.CharField(max_length=100, null=True, verbose_name='Ayak Kaplama Rengi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='indirimli_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='İndirimli Fiyat'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Ana Sayfada Göster'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Model İsmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='stokKodu',
            field=models.CharField(default='', max_length=100, verbose_name='Stok Kodu'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunRengi',
            field=models.CharField(default='', max_length=100, verbose_name='Şapka Rengi veya Deseni'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunresmi',
            field=models.ImageField(default='', upload_to='urunphoto/', verbose_name='1. Ürün Resmi (Zorunlu)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunresmiFour',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/', verbose_name='4. Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunresmiThree',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/', verbose_name='3. Ürün Resmi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunresmiTwo',
            field=models.ImageField(blank=True, default='', upload_to='urunphoto/', verbose_name='2. Ürün Resmi'),
        ),
    ]
