# Generated by Django 4.2.3 on 2023-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0034_alter_kurulum_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurulum',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
