# Generated by Django 4.2.3 on 2023-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0045_siparisurun_urun_resmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='teslimat_bilgileri',
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_adi',
            field=models.CharField(max_length=200, null=True, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_adres',
            field=models.CharField(max_length=200, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_ilce',
            field=models.CharField(max_length=200, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_sehir',
            field=models.CharField(max_length=200, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_soyadi',
            field=models.CharField(max_length=200, null=True, verbose_name='Soyadı'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_telefon',
            field=models.CharField(max_length=200, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='teslimat_bilgileri_ulke',
            field=models.CharField(max_length=200, null=True, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='siparisurun',
            name='urun_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='siparis_urun_resimleri/', verbose_name='Ürün Resmi'),
        ),
    ]
