# Generated by Django 4.2.3 on 2023-08-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0048_rename_gönderim_bilgisi_siparis_gonderim_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisurun',
            name='urun_stok_kodu',
            field=models.CharField(max_length=50, null=True, verbose_name='Ürün Stok Kodu'),
        ),
    ]
