# Generated by Django 4.1.7 on 2023-07-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_myuser_city_myuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
