# Generated by Django 4.2 on 2023-06-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anakategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anakategoriGorsel', models.ImageField(upload_to='headerphoto/')),
                ('anakategoriBaslik', models.CharField(max_length=50)),
            ],
        ),
    ]
