# Generated by Django 4.2 on 2023-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_urun_urunresmi_alter_urun_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urunresmi',
            field=models.ImageField(default='', upload_to='urunphoto/'),
        ),
    ]
