# Generated by Django 4.2 on 2023-06-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0008_urun_urunresmifour_urun_urunresmithree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stokKodu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunRengi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
