# Generated by Django 4.2 on 2023-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0010_urun_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='indirimli_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
