# Generated by Django 4.2 on 2023-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_wrapperone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('company_phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='footersocialmedia_photos/')),
                ('link', models.URLField(max_length=1000)),
            ],
        ),
    ]
