# Generated by Django 4.2 on 2023-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0016_footer_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='company_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
