# Generated by Django 4.2 on 2023-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0018_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='toplam',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
