# Generated by Django 4.2 on 2023-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0020_alter_sepet_toplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='ayakKaplama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
