# Generated by Django 4.2 on 2023-07-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0021_urun_ayakkaplama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='ayakKaplama',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
