# Generated by Django 4.2.3 on 2023-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0023_alter_anakategori_anakategorigorsel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='toplam',
            field=models.FloatField(null=True),
        ),
    ]
