# Generated by Django 4.2.3 on 2023-07-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0026_alter_socialmedia_options_alter_urun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anakategori',
            options={'verbose_name_plural': 'Anakategoriler'},
        ),
        migrations.AlterModelOptions(
            name='sepet',
            options={'verbose_name_plural': 'Sepetler'},
        ),
        migrations.AlterModelOptions(
            name='slogan',
            options={'verbose_name_plural': 'Ana Sayfa Header'},
        ),
        migrations.AlterModelOptions(
            name='wrapperone',
            options={'verbose_name_plural': 'Banner(Afiş)'},
        ),
    ]
