# Generated by Django 4.2.3 on 2023-07-31 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0027_alter_anakategori_options_alter_sepet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vizyonResim', models.ImageField(upload_to='hakkimzda/', verbose_name='Vizyon Resim')),
                ('vizyon', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vizyonumuz')),
                ('misyonResim', models.ImageField(upload_to='hakkimzda/', verbose_name='Misyon Resim')),
                ('misyon', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Misyonumuz')),
                ('degerlerimizResim', models.ImageField(upload_to='hakkimzda/', verbose_name='Değerlerimiz Resim')),
                ('degerlerimiz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Degerlerimiz')),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
