# Generated by Django 4.2.3 on 2023-08-03 11:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0030_mesafelisatisozlesmesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gizliliksozlesmesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gizlilikBaslik', models.CharField(max_length=150, null=True, verbose_name='Gizlilik ve Güvenlik Başlığı')),
                ('gizlilikmetni', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Gizlilik ve Güvenlik Metni')),
            ],
            options={
                'verbose_name_plural': 'Gizlilik ve Güvenlik Sözleşmesi',
            },
        ),
        migrations.CreateModel(
            name='Iptalveiade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iptalveiadeBaslik', models.CharField(max_length=150, null=True, verbose_name='İptal ve İade Koşulları Metni Başlığı')),
                ('iptalveiademetni', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İptal ve İade Koşulları Metni')),
            ],
            options={
                'verbose_name_plural': 'İptal ve İade Koşulları Metni',
            },
        ),
        migrations.AlterField(
            model_name='kvkkmetni',
            name='kvkkBaslik',
            field=models.CharField(max_length=100, null=True, verbose_name='KVKK Metni Başlığı'),
        ),
        migrations.AlterField(
            model_name='mesafelisatisozlesmesi',
            name='mesafeliBaslik',
            field=models.CharField(max_length=150, null=True, verbose_name='Mesafeli Satış Sözleşmesi Başlığı'),
        ),
        migrations.AlterField(
            model_name='mesafelisatisozlesmesi',
            name='mesafelimetni',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi Metni'),
        ),
        migrations.AlterField(
            model_name='uyelikmetni',
            name='uyelikBaslik',
            field=models.CharField(max_length=100, null=True, verbose_name='Üyelik Metni Başlığı'),
        ),
    ]
