# Generated by Django 4.2.3 on 2023-08-03 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0031_gizliliksozlesmesi_iptalveiade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoBaslik', models.CharField(max_length=150, null=True, verbose_name='Video Başlığı')),
                ('video_link', models.URLField()),
                ('kurulumResim', models.ImageField(null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi')),
                ('kurulumAciklamasi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kurulum Açıklaması')),
            ],
            options={
                'verbose_name_plural': 'Kurulum Bilgilendirme',
            },
        ),
    ]
