# Generated by Django 4.2.3 on 2023-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0032_kurulum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurulum',
            name='video_link',
        ),
        migrations.AddField(
            model_name='kurulum',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
