# Generated by Django 4.2.3 on 2023-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0036_alter_kurulum_kurulumresim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurulum',
            name='kurulumResim2',
            field=models.ImageField(blank=True, null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 2'),
        ),
        migrations.AddField(
            model_name='kurulum',
            name='kurulumResim3',
            field=models.ImageField(blank=True, null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 3'),
        ),
        migrations.AddField(
            model_name='kurulum',
            name='kurulumResim4',
            field=models.ImageField(blank=True, null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 4'),
        ),
        migrations.AddField(
            model_name='kurulum',
            name='kurulumResim5',
            field=models.ImageField(blank=True, null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 5'),
        ),
        migrations.AddField(
            model_name='kurulum',
            name='kurulumResim6',
            field=models.ImageField(blank=True, null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 6'),
        ),
        migrations.AlterField(
            model_name='kurulum',
            name='kurulumResim',
            field=models.ImageField(null=True, upload_to='kurulum/', verbose_name='Kurulum Resmi 1 (Zorunlu)'),
        ),
    ]
