# Generated by Django 4.2.3 on 2023-08-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0040_odeme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odeme',
            name='sepet',
        ),
        migrations.AddField(
            model_name='odeme',
            name='sepet',
            field=models.ManyToManyField(to='productsapp.sepet'),
        ),
    ]
