# Generated by Django 4.2.3 on 2023-08-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productsapp', '0042_remove_odeme_sepet_odeme_sepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat')),
                ('satinalma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Satın Alma Tarihi')),
                ('odeme_bilgisi', models.BooleanField(default=False, verbose_name='Ödeme Bilgisi')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
            },
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Birim Fiyat')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.urun')),
            ],
            options={
                'verbose_name_plural': 'Sipariş Ürünleri',
            },
        ),
        migrations.DeleteModel(
            name='Odeme',
        ),
        migrations.AddField(
            model_name='siparis',
            name='urunler',
            field=models.ManyToManyField(through='productsapp.SiparisUrun', to='productsapp.urun', verbose_name='Satın Alınan Ürünler'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
