# Generated by Django 4.2.3 on 2023-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0044_siparis_teslimat_bilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisurun',
            name='urun_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='siparis_urun_resimleri/', verbose_name='Ürön Resmi'),
        ),
    ]
