# Generated by Django 4.2.3 on 2023-08-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0047_siparis_gönderim_bilgisi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparis',
            old_name='gönderim_bilgisi',
            new_name='gonderim_bilgisi',
        ),
    ]
